import {
    Activity,
    BarChart3,
    Clock,
    Package,
    Target,
    User,
    Zap,
} from "lucide-react";

export const achievements = [
    {
        id: 1,
        name: "First Steps",
        description: "Completed your first ESP32 project",
        icon: Target,
        earned: false,
        progress: 0,
        total: 1,
        rarity: "common",
    },
    {
        id: 2,
        name: "Power Saver",
        description: "Implemented deep sleep in a project",
        icon: Zap,
        earned: false,
        progress: 0,
        total: 1,
        rarity: "uncommon",
    },
    {
        id: 3,
        name: "Network Master",
        description: "Built 5 WiFi-connected projects",
        icon: Activity,
        earned: false,
        progress: 0,
        total: 5,
        rarity: "rare",
    },
    {
        id: 4,
        name: "Component Collector",
        description: "Added 50+ components to inventory",
        icon: Package,
        earned: false,
        progress: 0,
        total: 50,
        rarity: "uncommon",
    },
    {
        id: 5,
        name: "Code Contributor",
        description: "Shared 10 code snippets",
        icon: Activity,
        earned: false,
        progress: 0,
        total: 10,
        rarity: "rare",
    },
    {
        id: 6,
        name: "Time Master",
        description: "100+ hours of development",
        icon: Clock,
        earned: false,
        progress: 0,
        total: 100,
        rarity: "epic",
    },
    {
        id: 7,
        name: "Analytics Pro",
        description: "Tracked 20+ project metrics",
        icon: BarChart3,
        earned: false,
        progress: 0,
        total: 20,
        rarity: "legendary",
    },
    {
        id: 8,
        name: "Community Helper",
        description: "Helped 5+ developers",
        icon: User,
        earned: false,
        progress: 0,
        total: 5,
        rarity: "rare",
    },
];
