name: Vercel Preview Comment

on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  comment:
    runs-on: ubuntu-latest
    # Only run if this is actually a pull request event
    if: github.event.pull_request.number != null
    steps:
      - uses: actions/checkout@v4
        with:
          # Checkout the main branch for security (pull_request_target best practice)
          ref: ${{ github.event.repository.default_branch }}
      - name: Run Vercel Preview Comment Action
        uses: ./.github/actions/vercel-preview-comment
        with:
          pr_number: ${{ github.event.pull_request.number }}
          repo_owner: ${{ github.repository_owner }}
          repo_name: ${{ github.event.repository.name }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
