name: Vercel Preview Comment

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Run Vercel Preview Comment Action
        uses: ./.github/actions/vercel-preview-comment
        with:
          pr_number: ${{ github.event.pull_request.number }}
          repo_owner: ${{ github.repository_owner }}
          repo_name: ${{ github.event.repository.name }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
