name: Vercel Preview Comment

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    outputs:
      vercel_url: ${{ steps.set-url.outputs.vercel_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Vercel Preview URL
        id: set-url
        run: |
          echo "vercel_url=https://esp32-dev-manager-git-${{ github.head_ref }}-${{ github.repository_owner }}.vercel.app" >> $GITHUB_OUTPUT

      # Add your actual Vercel deployment step here if needed

  comment:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Post Vercel Preview Comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            🚀 **Vercel Preview Available**
            🔗 [View Live Preview](${{ needs.build-and-deploy.outputs.vercel_url }})

            📱 Scan on mobile:
            ![QR Code](https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=${{ needs.build-and-deploy.outputs.vercel_url }})

            🧪 This preview is auto-generated for PR #${{ github.event.pull_request.number }}.
